[package]
name = "udp-protocol"
version = "0.1.0"
edition = "2024"

description = "UDP protocol stack implementation"
authors = ["Bedrock"]

[dependencies]
criterion = "0.6"

[[bench]]
name = "protocol_benchmark"
harness = false