[target.aarch64-unknown-linux-gnu]
linker = "/home/common/toolchain/rk356x/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc"
rustflags = [
  "-C", "link-arg=--sysroot=/home/common/toolchain/rk356x/sysroots/aarch64-poky-linux",
  "-C", "link-arg=-Wl,-rpath-link,/home/common/toolchain/rk356x/sysroots/aarch64-poky-linux/usr/lib",
]
ar = "/home/common/toolchain/rk356x/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-ar"