name: Build & Test Rust Project on Tag

on:
  push:
    tags:
      - "*"   # 匹配所有 tag

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build (debug)
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Upload Release Binary
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: target/release/
          if-no-files-found: error
